import type { Metadata } from "next";
import { El_Messiri } from "next/font/google";
import "./globals.css";

const elMessiri = El_Messiri({
  variable: "--font-el-messiri",
  subsets: ["arabic"],
})

export const metadata: Metadata = {
  title: "Fawaz Al Aranji",
  description: "Generated by Abdullah Hasson",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body
        className={`${elMessiri.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
